// Theme
export const THEME_SUCCESS = 'THEME_SUCCESS';

// Auth  
export const LOGIN_ACCOUNT = 'LOGIN_ACCOUNT';
export const LOGIN_ACCOUNT_SUCCESS = 'LOGIN_ACCOUNT_SUCCESS';
export const LOGIN_ACCOUNT_ERROR = 'LOGIN_ACCOUNT_ERROR';
export const UPDATE_FORGOT_PASSWORD = 'UPDATE_FORGOT_PASSWORD';
export const UPDATE_FORGOT_PASSWORD_SUCCESS = 'UPDATE_FORGOT_PASSWORD_SUCCESS';
export const UPDATE_FORGOT_PASSWORD_ERROR = 'UPDATE_FORGOT_PASSWORD_ERROR';
export const SIGNUP_USERS_ACCOUNT = 'SIGNUP_USERS_ACCOUNT';
export const POST_VERIFY_OTP = 'POST_VERIFY_OTP';
export const POST_VERIFY_OTP_ERROR = 'POST_VERIFY_OTP_ERROR';
export const USER_NEW_PASSWORD = 'USER_NEW_PASSWORD';
export const USER_NEW_PASSWORD_ERROR = 'USER_NEW_PASSWORD_ERROR';
export const USER_CHANGE_PASSWORD = 'USER_CHANGE_PASSWORD';
export const USER_CHANGE_PASSWORD_ERROR = 'USER_CHANGE_PASSWORD_ERROR';

// Crate board 
export const CREATE_BOARD_SUCCESS = 'CREATE_BOARD_SUCCESS';
export const CREATE_BOARD_ERROR = 'CREATE_BOARD_ERROR';
export const CREATE_BOARD_PROCESS = 'CREATE_BOARD_PROCESS';
export const GET_DEVICE_LIST = 'GET_DEVICE_LIST';
export const GET_DEVICE_LIST_SUCCESS = 'GET_DEVICE_LIST_SUCCESS';
export const GET_DEVICE_LIST_ERROR = 'GET_DEVICE_LIST_ERROR';
export const CREATE_BOARD_TO_ROOM = 'CREATE_BOARD_TO_ROOM';
export const CREATE_BOARD_TO_ROOM_SUCCESS = 'CREATE_BOARD_TO_ROOM_SUCCESS';
export const CREATE_BOARD_TO_ROOM_ERROR = 'CREATE_BOARD_TO_ROOM_ERROR';
export const UPDATE_BOARD_NAME = 'UPDATE_BOARD_NAME';
export const UPDATE_BOARD_NAME_ERROR = 'UPDATE_BOARD_NAME_ERROR';


// Get Switch List
export const GET_SWITCH_LIST = 'GET_SWITCH_LIST';
export const GET_SWITCH_LIST_DETAILS = 'GET_SWITCH_LIST_DETAILS';
export const GET_SWITCH_LIST_SUCCESS = 'GET_SWITCH_LIST_SUCCESS';
export const GET_SWITCH_LIST_ERROR = 'GET_SWITCH_LIST_ERROR';
export const UPDATE_EDIT_SWITCH_LIST = 'UPDATE_EDIT_SWITCH_LIST';
export const UPDATE_EDIT_SWITCH_LIST_SUCCESS = 'UPDATE_EDIT_SWITCH_LIST_SUCCESS';
export const UPDATE_EDIT_SWITCH_LIST_ERROR = 'UPDATE_EDIT_SWITCH_LIST_ERROR';

// Room ACTION
export const GET_ROOM_LIST = 'GET_ROOM_LIST';
export const GET_ROOM_LIST_ERROR = 'GET_ROOM_LIST_ERROR';
export const GET_ROOM_LIST_SUCCESS = 'GET_ROOM_LIST_SUCCESS';
export const CREATE_ROOM = 'CREATE_ROOM';
export const CREATE_ROOM_ERROR = 'CREATE_ROOM_ERROR';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';



// MQTT connection
export const GET_MQTT_SWITCH = 'GET_MQTT_SWITCH';
export const GET_MQTT_SWITCH_ERROR = 'GET_MQTT_SWITCH_ERROR';
export const GET_MQTT_SWITCH_SUCCESS = 'GET_MQTT_SWITCH_SUCCESS';
