// Theme
export const THEME_SUCCESS = 'THEME_SUCCESS';

// Auth login 
export const LOGIN_ACCOUNT = 'LOGIN_ACCOUNT';
export const LOGIN_ACCOUNT_SUCCESS = 'LOGIN_ACCOUNT_SUCCESS';
export const LOGIN_ACCOUNT_ERROR = 'LOGIN_ACCOUNT_ERROR';

// Auth sign UP
export const SIGNUP_USERS_ACCOUNT = 'SIGNUP_USERS_ACCOUNT';

// Crate board 
export const CREATE_BOARD_SUCCESS = 'CREATE_BOARD_SUCCESS';
export const CREATE_BOARD_ERROR = 'CREATE_BOARD_ERROR';
export const CREATE_BOARD_PROCESS = 'CREATE_BOARD_PROCESS';
export const GET_DEVICE_LIST = 'GET_DEVICE_LIST';
export const GET_DEVICE_LIST_SUCCESS = 'GET_DEVICE_LIST_SUCCESS';
export const GET_DEVICE_LIST_ERROR = 'GET_DEVICE_LIST_ERROR';

// Get Switch List
export const GET_SWITCH_LIST = 'GET_SWITCH_LIST';
export const GET_SWITCH_LIST_DETAILS = 'GET_SWITCH_LIST_DETAILS';
export const GET_SWITCH_LIST_SUCCESS = 'GET_SWITCH_LIST_SUCCESS';
export const GET_SWITCH_LIST_ERROR = 'GET_SWITCH_LIST_ERROR';

// Room ACTION
export const GET_ROOM_LIST = 'GET_ROOM_LIST';
export const GET_ROOM_LIST_ERROR = 'GET_ROOM_LIST_ERROR';
export const GET_ROOM_LIST_SUCCESS = 'GET_ROOM_LIST_SUCCESS';
export const CREATE_ROOM = 'CREATE_ROOM';
export const CREATE_ROOM_ERROR = 'CREATE_ROOM_ERROR';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';



