// Theme
export const THEME_SUCCESS = 'THEME_SUCCESS';

// Auth login 
export const LOGIN_ACCOUNT = 'LOGIN_ACCOUNT';
export const LOGIN_ACCOUNT_SUCCESS = 'LOGIN_ACCOUNT_SUCCESS';
export const LOGIN_ACCOUNT_ERROR = 'LOGIN_ACCOUNT_ERROR';

// Auth sign UP
export const SIGNUP_USERS_ACCOUNT = 'SIGNUP_USERS_ACCOUNT';

// Crate board 
export const CREATE_BOARD_SUCCESS = 'CREATE_BOARD_SUCCESS';
export const CREATE_BOARD_ERROR = 'CREATE_BOARD_ERROR';
export const CREATE_BOARD_PROCESS = 'CREATE_BOARD_PROCESS';


